# Generated by Django 3.2 on 2021-04-11 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 11, 19, 20, 26, 177997)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
